---
- hosts: localhost
  connection: local
  vars_files:
    - vars/vsphere-homelab.yml
  tasks:
    - block:
        - name: Create Sample nodejs app
          include_role: name=create-sample-nodejs-app
        - name: Create Sample springboot app
          include_role: name=create-sample-springboot-app