---
- hosts: localhost
  connection: local
  vars_files:
    - vars/mirror-images.yml
  tasks:
    - name: Mirror Images
      shell: "oc adm release mirror -a {{LOCAL_SECRET_JSON}} --from={{RELEASE_IMAGE}} --to-release-image={{LOCAL_REGISTRY}}/{{LOCAL_REPOSITORY}}:{{OCP_RELEASE}} --to={{LOCAL_REGISTRY}}/{{LOCAL_REPOSITORY}}"