---
# instructions as per https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client
- block:
    - include: setup.yml

    - name: Create Openshift nfs rbac
      shell: "oc create -f {{playbook_dir}}/roles/create-dynamic-nfs-provisioner/files/nfs-rbac.yaml"

    - name: Ensure permissions
      shell: "oc adm policy add-scc-to-user hostmount-anyuid system:serviceaccount:default:nfs-client-provisioner"

    - name: Create the NFS client provisioner yaml
      template:
        src: ../templates/nfs-deployment.yaml.j2
        dest: "{{ tmpdir }}/nfs-deployment.yaml"

    - name: Create the NFS client provisioner yaml
      shell: "oc create -f {{ tmpdir }}/nfs-deployment.yaml"

    - name: Create the NFS storage class
      shell: "oc create -f {{playbook_dir}}/roles/create-dynamic-nfs-provisioner/files/nfs-storageclass.yaml -n default"

    - name: Wait until NFS client provisioner is running
      shell: "oc get pods --field-selector \"status.phase=Running\" -n default -l app=nfs-client-provisioner -o name"
      ignore_errors: yes
      retries: 15
      delay: 60
      register: result
      until: result.rc == 0

    - name: Create test PV claim
      shell: "oc create -f {{playbook_dir}}/roles/create-dynamic-nfs-provisioner/files/nfs-test-claim.yaml -n default"

    - name: Create test pod
      shell: "oc create -f {{playbook_dir}}/roles/create-dynamic-nfs-provisioner/files/nfs-test-pod.yaml -n default"

    - name: Ensure test pod has suceeded
      shell: "oc get pods --field-selector \"status.phase=Succeeded\" -n default -l apstorage.test.type=nfs -o name"
      ignore_errors: yes
      retries: 5
      delay: 60
      register: result
      until: result.rc == 0

    - include: cleanup.yml

